### ISSUE TITLE
GUI Not Responding

### ISSUE THREAD

**Issue by rationalcoder** [yse/easy_profiler#75]
Earlier, there was an issue fixed where the GUI crashed if you hit cancel in the middle of receiving blocks. That is fixed, sure, but the GUI still goes unresponsive for the period of time it would have taken to finish receiving the blocks, which doesn't help much. 

There should be changes to the networking code such that a message is sent to the profiled application to cancel the transfer and reset all state, instead of whatever is being done now.

**Comment by cas4ey** [comment]
Done, testing required

**Comment by rationalcoder** [comment]
Okay, so this might be fixed for other people, but it is still broken for me.
I should have tested it before assuming it was fixed, but, looking at the code changes, everything seems reasonable.

Can you provide me a high-level overview of your solution, so I can see if it is another platform related issue? For example, is the solution mainly GUI side, application side, or both? I ask because I had to hack GCC-4.9.4 for ARMv5 b/c it has a bug that makes `std::future` unsupported. It is possible that I could have messed something up.

**Comment by cas4ey** [comment]
The changes affected only core.
When GUI send request to stop profiling, core begins asynchronous dumping and sets 500ms timeout for receive socket to let it possible to cancel dumping.

You can look at couple of moments:
- Core uses `std::async` and `std::future` for asynchronous dumping;
- Core sets timeout for socket when dumping begins and resets timeout when dumping ends.

Main changes were made to `ProfileManager::listen()` function.

I think the reason is that timeout was not properly set for the socket and it is getting blocked on `receive()`.

**Comment by cas4ey** [comment]
When GUI send request to stop profiling, core begins asynchronous dumping and sets 500ms timeout for receive socket to let it possible to cancel dumping.

You can take a look at couple of moments:
- Core uses `std::async` and `std::future` for asynchronous dumping;
- Core sets timeout for socket when dumping begins and resets timeout when dumping ends.

Main changes were made to `ProfileManager::listen()` function.

Maybe `std::async` is not really async despite of it was explicitly told to `std::launch::async`.
Or maybe timeout was not properly set for the socket and it is getting blocked on `receive()`.

**Comment by cas4ey** [comment]
@rationalcoder are there any news?

**Comment by rationalcoder** [comment]
@cas4ey No, sorry, I have been really busy. Have you tried collecting a really large amount of blocks and canceling the dialog, confirming that your patch works on you machine?
